### ISSUE TITLE
Status of Mopidy-Mixcloud?

### ISSUE THREAD

**Issue by 01tot10** [unusualcomputers/unusualcomputers#4]
Hello hello! 

I ran into this plugin when searching for ways to include Mixcloud into the supported sources for Mopidy.
Even though the plugin installs, I'm only getting errors from the mopidy log when trying to look for content to play through it.

Is it so that Mopidy-Mixcloud is maybe not really functional at this point in time?
Maybe it's also related to the relative recent switch of Mopidy from Python 2 to Python 3? 

Just curious since none of this is really stated anywhere here in the Mopidy-Mixcloud documentation!

Cheers!

**Comment by unusualcomputers** [comment]
Hi

Sorry for taking ages to reply to this, I have not been maintaining this
much for a while, and then had covid (still recovering).

I don't know why it hasn't been working :( I will try to find time before
end of year to go through it and fix what I can.

I will be in touch as soon as I have any news.

In the meantime, thanks very much for looking into it and reporting the
problems.

**Comment by 01tot10** [comment]
Hey @unusualcomputers! 

Thanks for getting back on the topic (and sorry to hear what you've gone through)!
Absolutely no stress obviously regarding this! But nice to hear you might have time to have a look at some point!
In the meanwhile I'm using `upmpdcli`* as a workaround to stream Mixcloud from my laptop. While not as smooth as a direct client, at least there's something :).

Cheers!
* https://www.lesbonscomptes.com/upmpdcli/

**Comment by vamostamos** [comment]
Hey @unusualcomputers! 
It is really good that such extension exists for Mopidy. Thank you for that. Wish you quick recovery.

**Comment by unusualcomputers** [comment]
Hello again,

I finally found a bit of time to look into this and it turns out it took
quite a bit of work to catch up with all the changes by mixcloud, and I
added a few more bits and pieces.

It should now be working in versions before mopidy 3. I will start working
on getting the mopidy 3 compliant version out asap, but if you are still
using older ones, you should be able to use it now.

The documentation on GitHub is updated too. The best way to go about it is
to uninstall (sudo pip uninstall Mopidy-Mixcloud) and install again (sudo
pip install Mopidy-Mixcloud).

I would very much appreciate reports of any problems

**Comment by unusualcomputers** [comment]
It should now work for Mopidy 3 as well. use:

sudo python3 -m pip install Mopidy-Mixcloud 

to install for Mopidy 3 and:

sudo pip install Mopidy-Mixcloud

for Mopidy 2

**Comment by 01tot10** [comment]
Hey @unusualcomputers! 

Thanks a lot for having a look at the issue! I just upgraded the external in my mopidy-instance and can confirm that everything is working and I had a great time making pizza-dough with some mixcloud-loveliness playing in the background just now :).

Thanks so much for your efforts! I'm sure this external will come of great use in the future!

**Comment by unusualcomputers** [comment]
Thanks very much for testing it and letting me know, I cannot think of a
better use for than to provide background sound while making pizza dough!

All the best.

**Comment by 01tot10** [comment]
Hey @unusualcomputers! 

It appears to me, that `Mopidy-Mixcloud` is broken again :sweat:.

Here's the output from playing a track from Mixcloud

```
[mixcloud] lylradio_get-in-the-pobotron-080923-wpoborsk: Downloading JSON metadata
ERROR: lylradio_get-in-the-pobotron-080923-wpoborsk: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR    [Core-10] mopidy.core.playback MopidyMixcloud backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 904, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/mixcloud.py", line 129, in _real_extract
    }''', track_id, username, slug)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/mixcloud.py", line 32, in _call_api
    }''' % (lookup_key, username, ', slug: "%s"' % slug if slug else '', object_fields)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 897, in _download_json
    expected_status=expected_status)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 881, in _download_json_handle
    fatal=fatal), urlh
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 908, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: lylradio_get-in-the-pobotron-080923-wpoborsk: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy_mixcloud/mixcloud_data.py", line 202, in get_stream_url
    info=ydl.extract_info(mixcloud_prefix+track_uri,download=False)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: lylradio_get-in-the-pobotron-080923-wpoborsk: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/playback.py", line 352, in _change
    if not backend.playback.change_track(pending_tl_track.track).get():
  File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy/backend.py", line 331, in change_track
    uri = self.translate_uri(track.uri)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_mixcloud/mopidy_mixcloud.py", line 201, in translate_uri
    return get_stream_url(uri)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_mixcloud/mixcloud_data.py", line 204, in get_stream_url
    logger.warning(de)
NameError: name 'logger' is not defined
WARNING  [Core-10] mopidy.core.tracklist Track is not playable: mixcloud:track:/lylradio/get-in-the-pobotron-080923-wpoborsk/
```

I'm running
- `Mopidy (3.4.1)`
- `setuptools (40.8.0)`
- `Pykka (2.0.3)`
- `youtube-dl (2021.1.24.1)`.

Could it be that the updated versions of the required packages broke the older `Mopidy-Mixcloud`?

**Comment by nbx3** [comment]
> Hey @unusualcomputers!
> 
> It appears to me, that `Mopidy-Mixcloud` is broken again 😓.
> 
> Here's the output from playing a track from Mixcloud
> 
> ```
> [mixcloud] lylradio_get-in-the-pobotron-080923-wpoborsk: Downloading JSON metadata
> ERROR: lylradio_get-in-the-pobotron-080923-wpoborsk: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ERROR    [Core-10] mopidy.core.playback MopidyMixcloud backend caused an exception.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 904, in _parse_json
>     return json.loads(json_string)
>   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
>     ie_result = ie.extract(url)
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/mixcloud.py", line 129, in _real_extract
>     }''', track_id, username, slug)
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/mixcloud.py", line 32, in _call_api
>     }''' % (lookup_key, username, ', slug: "%s"' % slug if slug else '', object_fields)
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 897, in _download_json
>     expected_status=expected_status)
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 881, in _download_json_handle
>     fatal=fatal), urlh
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/extractor/common.py", line 908, in _parse_json
>     raise ExtractorError(errmsg, cause=ve)
> youtube_dl.utils.ExtractorError: lylradio_get-in-the-pobotron-080923-wpoborsk: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/mopidy_mixcloud/mixcloud_data.py", line 202, in get_stream_url
>     info=ydl.extract_info(mixcloud_prefix+track_uri,download=False)
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 799, in extract_info
>     return self.__extract_info(url, ie, download, extra_info, process)
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
>     self.report_error(compat_str(e), e.format_traceback())
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 628, in report_error
>     self.trouble(error_message, tb)
>   File "/usr/local/lib/python3.7/dist-packages/youtube_dl/YoutubeDL.py", line 598, in trouble
>     raise DownloadError(message, exc_info)
> youtube_dl.utils.DownloadError: ERROR: lylradio_get-in-the-pobotron-080923-wpoborsk: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/mopidy/core/playback.py", line 352, in _change
>     if not backend.playback.change_track(pending_tl_track.track).get():
>   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
>     _compat.reraise(*self._data['exc_info'])
>   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
>     raise value
>   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
>     response = self._handle_receive(envelope.message)
>   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
>     return callee(*message.args, **message.kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/mopidy/backend.py", line 331, in change_track
>     uri = self.translate_uri(track.uri)
>   File "/usr/local/lib/python3.7/dist-packages/mopidy_mixcloud/mopidy_mixcloud.py", line 201, in translate_uri
>     return get_stream_url(uri)
>   File "/usr/local/lib/python3.7/dist-packages/mopidy_mixcloud/mixcloud_data.py", line 204, in get_stream_url
>     logger.warning(de)
> NameError: name 'logger' is not defined
> WARNING  [Core-10] mopidy.core.tracklist Track is not playable: mixcloud:track:/lylradio/get-in-the-pobotron-080923-wpoborsk/
> ```
> 
> I'm running
> 
>     * `Mopidy (3.4.1)`
> 
>     * `setuptools (40.8.0)`
> 
>     * `Pykka (2.0.3)`
> 
>     * `youtube-dl (2021.1.24.1)`.
> 
> 
> Could it be that the updated versions of the required packages broke the older `Mopidy-Mixcloud`?

Check my pull request

**Comment by 01tot10** [comment]
> Check my pull request

Ah, perfect, thanks @nbx3! Checking out and installing from https://github.com/unusualcomputers/unusualcomputers/pull/5 fixes the issue. Superb!
